### ISSUE TITLE
Why does the modified transformer model and transformer model have the same code in the timing prediction folder？

### ISSUE THREAD

**Issue by liu12138666** [YihongDong/FAN#1]
Why does the modified transformer model and transformer model have the same code in the timing prediction folder？

**Comment by YihongDong** [comment]
We only replace the MLP in Transformer with FAN, without making any other changes to the architecture of Transformer. For further details, please refer to [`Timeseries_Forecasting/layers/Transformer_EncDec.py`](https://github.com/YihongDong/FAN/blob/main/Timeseries_Forecasting/layers/Transformer_EncDec.py) , where the experimental setting exp_setting = 0 corresponds to the standard Transformer, while exp_setting = 2 refers to the Transformer with FAN (Gated), and exp_setting = 4 represents the Transformer with FAN.
