### ISSUE TITLE
the difference between the external FANlayer and the FANlayer in Timeseries_Forecasting

### ISSUE THREAD

**Issue by hems354** [YihongDong/FAN#2]
Hello, what is the difference between the external FANlayer and the FANlayer in Timeseries_Forecasting? I want to process my own periodic series, which one should I use?

**Comment by YihongDong** [comment]
Thank you for your attention to our work. The FANlayer in Timeseries_Forecasting represents the version directly utilized in our experiments, while the external FANlayer is the revised version that adds comments and hyperparameter adjustments. We recommend that you use [`the external FANlayer`](https://github.com/YihongDong/FAN/blob/main/FANLayer.py).

**Comment by hems354** [comment]
Thank you very much for your reply. Your work has given me great inspiration. Thank you again.
