### ISSUE TITLE
How is the performance of FAN in audio/speech modeling?

### ISSUE THREAD

**Issue by sophiefy** [YihongDong/FAN#4]
Thank you for open-sourcing this inpiring work. FAN seems promising in audio/speech modeling, like integrating it into a vocoder. Is there any experiment on this?

**Comment by YihongDong** [comment]
Thanks for your attention to our work. We will take it into account and we also encourage you to explore this avenue! We would be happy to hear about your findings and discuss with us if you have any problems in relation to FAN.
