### ISSUE TITLE
请教一下，使用提供的工程测试transformer，结果和论文想差很多，想问一下问题出在哪里了？

### ISSUE THREAD

**Issue by scjlove** [YihongDong/FAN#6]
使用的提供工程的代码的transformer模型，测试时序数据集weather结果和文章差很远？想请教一下](url)
<img width="509" alt="屏幕截图 2024-12-18 195911" src="https://github.com/user-attachments/assets/b3ab47af-f473-4e28-9eae-77450353a085" />

**Comment by YihongDong** [comment]
抱歉，目前还没有人提出这个问题。根据您当前的描述，我也无法确定原因。请问您是否进行了任何修改？如果方便的话，麻烦您提供您使用的完整源代码和环境信息，以便我们进一步研究。最后，感谢您对我们工作的关注。

**Comment by scjlove** [comment]
<img width="264" alt="屏幕截图 2024-12-18 214155" src="https://github.com/user-attachments/assets/a2fea856-4b53-4f96-8bcd-5e4e46d19ace" />
这个是环境信息

**Comment by scjlove** [comment]
修改了exp_main.py的
# from models import Informer, Autoformer, Transformer, Reformer, Modified_Transformer
from models import Transformer,  Modified_Transformer , Dlinear
model_dict = {
            # 'Autoformer': Autoformer,
            'Transformer': Transformer,
            # 'Informer': Informer,
            # 'Reformer': Reformer,
            'Modified_Transformer': Modified_Transformer,
            'Dlinear': Dlinear,
        }
脚本信息：就是使用工程提供的Modified_Transformer.sh

**Comment by scjlove** [comment]
expset0_weather_96_96_Dlinear_custom_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0  
mse:0.19874955713748932, mae:0.2579246461391449

expset0_weather_96_192_Dlinear_custom_ftM_sl96_ll48_pl192_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0  
mse:0.2391793429851532, mae:0.29638028144836426

expset0_weather_96_336_Dlinear_custom_ftM_sl96_ll48_pl336_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0  
mse:0.2850452661514282, mae:0.3339860141277313

expset0_weather_96_720_Dlinear_custom_ftM_sl96_ll48_pl720_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0  
mse:0.34900274872779846, mae:0.384647935628891

expset2_weather_96_96_Dlinear_custom_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0  
mse:0.8043999075889587, mae:0.6794977188110352

expset2_weather_96_192_Dlinear_custom_ftM_sl96_ll48_pl192_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0  
mse:0.5325034260749817, mae:0.5486599802970886

expset2_weather_96_336_Dlinear_custom_ftM_sl96_ll48_pl336_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0  
mse:0.8743048310279846, mae:0.7217326760292053

expset2_weather_96_720_Dlinear_custom_ftM_sl96_ll48_pl720_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0  
mse:0.6266176104545593, mae:0.6042516231536865
直接使用FANLayer替换linear效果也会差很多
这里是修改的代码：
if exp_setting == 0:
                self.Linear_Seasonal = nn.Linear(self.seq_len, self.pred_len)
                self.Linear_Trend  = nn.Linear(self.seq_len, self.pred_len)
            elif exp_setting == 2:
                self.Linear_Seasonal = FANLayer(input_dim=self.seq_len, output_dim=self.pred_len, with_gate=True)
                self.Linear_Trend = FANLayer(input_dim=self.seq_len, output_dim=self.pred_len, with_gate=True)
            elif exp_setting == 4:
                self.Linear_Seasonal = FANLayer(input_dim=self.seq_len, output_dim=self.pred_len, with_gate=False)
                self.Linear_Trend = FANLayer(input_dim=self.seq_len, output_dim=self.pred_len, with_gate=False)
麻烦您了。

**Comment by YihongDong** [comment]
收到

**Comment by YihongDong** [comment]
抱歉，我们未能复现您的当前结果，但我们发现通过增加 batch size  (如将 batch size 从 32 调整至 256）可以显著提升模型性能。具体实验结果如下图所示，您或许也可以尝试一下？另外，我们已更新了相关代码，供您参考。

<img width="468" alt="image" src="https://github.com/user-attachments/assets/59c8b569-158a-4ab7-92ba-cc878fa3d1bf" />

**Comment by YihongDong** [comment]
如果我没理解错，这应该是另外一个问题。FAN Layer应该是用来替换MLP Layer的，我建议使用完整的FAN来替换单独的linear（即在linear之前增加一层FAN Layer并调整相关的超参数如dim等如需保证参数量一致）。

> expset0_weather_96_96_Dlinear_custom_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0 mse:0.19874955713748932, mae:0.2579246461391449
> 
> expset0_weather_96_192_Dlinear_custom_ftM_sl96_ll48_pl192_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0 mse:0.2391793429851532, mae:0.29638028144836426
> 
> expset0_weather_96_336_Dlinear_custom_ftM_sl96_ll48_pl336_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0 mse:0.2850452661514282, mae:0.3339860141277313
> 
> expset0_weather_96_720_Dlinear_custom_ftM_sl96_ll48_pl720_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0 mse:0.34900274872779846, mae:0.384647935628891
> 
> expset2_weather_96_96_Dlinear_custom_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0 mse:0.8043999075889587, mae:0.6794977188110352
> 
> expset2_weather_96_192_Dlinear_custom_ftM_sl96_ll48_pl192_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0 mse:0.5325034260749817, mae:0.5486599802970886
> 
> expset2_weather_96_336_Dlinear_custom_ftM_sl96_ll48_pl336_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0 mse:0.8743048310279846, mae:0.7217326760292053
> 
> expset2_weather_96_720_Dlinear_custom_ftM_sl96_ll48_pl720_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0 mse:0.6266176104545593, mae:0.6042516231536865 直接使用FANLayer替换linear效果也会差很多 这里是修改的代码： if exp_setting == 0: self.Linear_Seasonal = nn.Linear(self.seq_len, self.pred_len) self.Linear_Trend = nn.Linear(self.seq_len, self.pred_len) elif exp_setting == 2: self.Linear_Seasonal = FANLayer(input_dim=self.seq_len, output_dim=self.pred_len, with_gate=True) self.Linear_Trend = FANLayer(input_dim=self.seq_len, output_dim=self.pred_len, with_gate=True) elif exp_setting == 4: self.Linear_Seasonal = FANLayer(input_dim=self.seq_len, output_dim=self.pred_len, with_gate=False) self.Linear_Trend = FANLayer(input_dim=self.seq_len, output_dim=self.pred_len, with_gate=False) 麻烦您了。

**Comment by scjlove** [comment]
transformer可以了，谢谢您的解答。
